# Generated by Django 2.2.4 on 2020-11-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='album',
        ),
        migrations.DeleteModel(
            name='music',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='result',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
